package com.jotnar.ui.theme

import androidx.compose.ui.graphics.Color

// Default palette (baby pink)
val PrimaryLight = Color(0xFFBC4B7A)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFFFD9E5)
val OnPrimaryContainerLight = Color(0xFF3E0022)
val SecondaryLight = Color(0xFF74565E)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFFFD9E1)
val OnSecondaryContainerLight = Color(0xFF2B151C)
val TertiaryLight = Color(0xFF7C5635)
val OnTertiaryLight = Color(0xFFFFFFFF)
val SurfaceLight = Color(0xFFFFF8F8)
val OnSurfaceLight = Color(0xFF201A1B)
val SurfaceVariantLight = Color(0xFFF2DDE2)
val OnSurfaceVariantLight = Color(0xFF514347)
val ErrorLight = Color(0xFFBA1A1A)

val PrimaryDark = Color(0xFFFFB0CB)
val OnPrimaryDark = Color(0xFF631D3E)
val PrimaryContainerDark = Color(0xFF803356)
val OnPrimaryContainerDark = Color(0xFFFFD9E5)
val SecondaryDark = Color(0xFFE3BDC5)
val OnSecondaryDark = Color(0xFF422931)
val SecondaryContainerDark = Color(0xFF5B3F47)
val OnSecondaryContainerDark = Color(0xFFFFD9E1)
val TertiaryDark = Color(0xFFEFBD94)
val OnTertiaryDark = Color(0xFF48290C)
val SurfaceDark = Color(0xFF191113)
val OnSurfaceDark = Color(0xFFEDE0E1)
val SurfaceVariantDark = Color(0xFF514347)
val OnSurfaceVariantDark = Color(0xFFD5C2C6)
val ErrorDark = Color(0xFFFFB4AB)
